### ISSUE TITLE
Bug in pagination system of browse page

### ISSUE THREAD

**Issue by mishapaauw** [ag-computational-bio/bakrep-web#80]
Hi, thanks for compiling this excellent resource! I'm sure this will be useful for many people.

I noticed a bug on the 'Browse' page. The pagination system does not seem to work, the table shows the same strains regardless of the page I select. Example screenshots with the last two rows, on page 1 and 2:

![Screenshot 2024-11-06 at 10 02 59](https://github.com/user-attachments/assets/a6ce5858-6fcd-416c-b43d-b3df552ed88e)
![Screenshot 2024-11-06 at 10 03 27](https://github.com/user-attachments/assets/ce0e4fec-53d4-45ea-a977-ff213026c71d)

**Comment by lukasjelonek** [comment]
I can confirm the problem and will take a look into it.

**Comment by lukasjelonek** [comment]
I identified the problem and fixed it. 

@mishapaauw Does it now work for you?

**Comment by mishapaauw** [comment]
Yes it does! That's a fast fix.  I'll close the issue.
